### ISSUE TITLE
Images are generated in some odd language

### ISSUE THREAD

**Issue by sujitdmello** [openai/dalle-2-preview#25]
I asked Dall-E the following:

"Octoberfest invitation with the words 'Saturday October 14th - Come enjoy traditional German beers and food at the DMello residence' in English"

and it generated the following:

![image](https://github.com/openai/dalle-2-preview/assets/4335762/f43aa2fa-fd78-4305-b8b8-7cb968708cba)

I've checked and my language in my profile is set to US-en. Why is it generating output in some odd language? I don't recognize the script unfortunately.

Seems to do this odd script for any image I request. Is there some setting I am missing?

**Comment by woctezuma** [comment]
Nothing unusual as DALLE generates images here with something which looks like text but without actually knowing the language.

**Comment by sujitdmello** [comment]
Not what I expected but appreciate the clarification - I thought I was going a bit crazy. I did discover my browser profile had Dutch as a third language (not sure why as I don't know the language) so I thought maybe that was being picked up by mistake but even after removing it and clearing browser cache etc. it did not seem to help.
